### ISSUE TITLE
CountMatrix

### ISSUE THREAD

**Issue by soodoku** [nfrerebeau/tabula#11]
**Describe the bug**
In the man page for the function, you write: "Numeric values are rounded to zero decimal places and then coerced to integer as by as.integer."

**To Reproduce**
A minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

```
CountMatrix(data = 1.1, nrow = 1)
```
```
Error: "CountMatrix" object initialization:
*  'data' must contain whole numbers.
```
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nfrerebeau** [comment]
The documentation is wrong. It is likely better to return an error rather than modify the user's data.

**Comment by soodoku** [comment]
glad. 

one small thing:

if i put a negative number, it says it must be a positive whole number, which excludes 0.

could be: only 0 or positive whole numbers allowed.
