### ISSUE TITLE
JOSS

### ISSUE THREAD

**Issue by soodoku** [nfrerebeau/tabula#15]
Hey @nfrerebeau: I have created a few issues. when you get a chance take a look. The key thing that is missing in the paper = 

"State of the field: Do the authors describe how this software compares to other commonly-used packages?" Specifically, can you speak to all the other packages tailored toward ecologists etc. like 
https://github.com/vegandevs/vegan (I don't know as much about the field)

For the package, the key thing that is concerning = re-implementation of classic but simple algorithms, like shannon diversity, etc. it may be useful to import robust implementations? I don't know if they exist so suspect that they do.

The key thing missing from the package = whenever stat. tests are done, there is insufficient detail in the man pages about the assumptions and what precisely happened. There are some cites. But useful to write in a more expanded fashion what was done and return an object that has, for instance, all the estimates from each of the bootstrapped sample. 

Please disagree with whatever doesn't make sense. I don't want you to do anything that is not adding value. My aim is just to help make the package better.

**Comment by nfrerebeau** [comment]
> For the package, the key thing that is concerning = re-implementation of classic but simple algorithms, like shannon diversity, etc. it may be useful to import robust implementations? I don't know if they exist so suspect that they do.

I have added three new methods (`index_heterogeneity`, `index_evenness` and `index_richness` - `diversity`, `evenness` and `richness` are now deprecated) that return the diversity index estimates as well as the jackknifed and bootstrapped statistics. These estimates can be compared to simulated assemblages and plotted for graphical inspection.

**Comment by soodoku** [comment]
cool. 

tbh, my point didn't require as much work. i was just saying that some other people may have already produced robust implementations. by robust, i narrowly meant things that catch the run of the mill errors and prevent things from exploding etc. --- ala log 0, etc. 

but this looks good. i still need to check the functionality but it looks good to me.

**Comment by nfrerebeau** [comment]
> "State of the field: Do the authors describe how this software compares to other commonly-used packages?" Specifically, can you speak to all the other packages tailored toward ecologists etc. like
https://github.com/vegandevs/vegan (I don't know as much about the field)

I have added a paragraph to clarify this point.

**Comment by soodoku** [comment]
super. feel free to close it out.
