### ISSUE TITLE
R version 3.6.3 (2020-02-29)

### ISSUE THREAD

**Issue by airesarch** [nfrerebeau/tabula#19]
I commonly used Tabula on "R version 3.4.4" to get plot_ford(). Now when applying on "R version 3.6.3 (2020-02-29)" I get this:

compiegne%>%
  as_count() %>%
  plot_ford()

Result: 
"Error in `$<-.data.frame`(`*tmp*`, "data", value = numeric(0)) : 
  replacement has 0 rows, data has 160"

Do I missing something?
Thanks for your effort!

**Comment by nfrerebeau** [comment]
I'm glad to hear that tabula is useful for you!

I am currently working on a dependency of tabula and I had to introduce breaking changes. All these problems will be fixed for the next version of tabula (coming soon), but in the meantime the best thing to do is to install the latest release : 
```
remotes::install_github("nfrerebeau/tabula", ref = "v1.5.1")
```
Let me know if you have any other issues.

**Comment by nfrerebeau** [comment]
Everything should work now by installing the development version:

```
remotes::install_github("nfrerebeau/tabula")
```
