### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by tsdye** [nfrerebeau/tabula#2]
ERROR: dependency ‘car’ is not available for package ‘FactoMineR’
* removing ‘/home/dk/R/x86_64-pc-linux-gnu-library/3.4/FactoMineR’
ERROR: dependency ‘FactoMineR’ is not available for package ‘tabula’
* removing ‘/home/dk/R/x86_64-pc-linux-gnu-library/3.4/tabula’

The downloaded source packages are in
	‘/tmp/Rtmp5iMKEO/downloaded_packages’
Warning messages:
1: In install.packages(c("tabula", "khroma")) :
  installation of package ‘openxlsx’ had non-zero exit status
2: In install.packages(c("tabula", "khroma")) :
  installation of package ‘rio’ had non-zero exit status
3: In install.packages(c("tabula", "khroma")) :
  installation of package ‘car’ had non-zero exit status
4: In install.packages(c("tabula", "khroma")) :
  installation of package ‘FactoMineR’ had non-zero exit status
5: In install.packages(c("tabula", "khroma")) :
  installation of package ‘tabula’ had non-zero exit status

**Comment by nfrerebeau** [comment]
Is it related to the installation of the CRAN or GitHub version? I can't reproduce the same issue on my side. Do you have an error message for the installation of 'car'?

**Comment by tsdye** [comment]
I installed on another machine without errors, so the problem is on my end.  I'll get back when I track it down.

**Comment by tsdye** [comment]
An old lock was in the way.  Removed that and all is well.  Sorry for the noise.
